#!/bin/bash

USERNAME=$1
ARG_NUM=$#

if [ $ARG_NUM -ne 1 ]; then
    echo "Usage: $0 <a user name to be registered>"
    exit 1
fi

echo
echo "========================================================="
echo "Enrolling the intermediate CA using these credentials:"
echo "  username: admin.ica"
echo "  password: adminpw"
echo "========================================================="
echo
fabric-ca-client enroll -u http://admin.ica:adminpw@ica:7054
if [ $? != 0 ]; then
    echo "Failed"
    exit 1
else
    echo "Enrolled"
fi
echo

echo
id_attrs='hf.Revoker=true,admin=true:ecert'
echo "====================================================="
echo "Registering this user using these credentials."
echo "  id.type: user"
echo "  id.name: $USERNAME"
echo "  id.affliliation: org1.department1"
echo "  id.attrs: '$id_attrs'"
echo "====================================================="
echo
pword=$(fabric-ca-client register --id.name $USERNAME \
                          --id.type user \
                          --id.affiliation org1.department1 \
                          --id.attrs $id_attrs)
if [ $? != 0 ]; then
    echo "Failed"
    exit 1
else
    echo "Registered"
fi
echo


echo "====================================================="
echo "Enroll this credential $USERNAME with password $pword"
echo "generated by the intermediate CA for use in this client"
echo "====================================================="
fabric-ca-client enroll -u http://"$USERNAME":"${pword:10}"@ica:7054
if [ $? != 0 ]; then
    echo "Failed"
    exit 1
else
    echo "Enrolled"
fi
echo