title: "Fabric CA analysis"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

aux_links:
    "Click here to see the codes in GitHub":
      - "https://github.com/openconsentia/fabric-ca-analysis"