title: "Fabric CA analysis"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

aux_links:
    "Fabric CA analysis on GitHub":
      - "//github.com/openconsentia/fabric-ca-analysis"